function plot_drug(t1, y1, b1, t2, y2, b2, t3, y3, b3, series_name)
    fig = tiledlayout(3, 2);
    xlabel(fig, "time (hrs)");
    ylabel(fig, "Concentration [nmol]")
    
    nexttile;
    plot(...       
        t1, y1(:, 1), ...
        t2, y2(:, 1), ...
        t3, y3(:, 1), ...
        'LineWidth', 3 ...
    );
    legend(series_name);
    title("Free Drug Concentration in Blood");
    
    nexttile;
    plot(...
        t1, sum(y1(:, 1:2), 2), ...
        t2, sum(y2(:, 1:2), 2), ...
        t3, sum(y3(:, 1:2), 2), ...
        'LineWidth', 3 ...
    );
    legend(series_name);
    title("Concentration of Total Drug in Blood");
    
    nexttile;
    plot(...
        t1, y1(:, 3), ...
        t2, y2(:, 3), ...
        t3, y3(:, 3), ...
        'LineWidth', 3 ...
    );
    legend(series_name);
    title("Concentration of Free Drug in Large Tumor");
    
    nexttile
    plot(...
        t1, y1(:, 4), ...
        t2, y2(:, 4), ...
        t3, y3(:, 4), ...
        'LineWidth', 3 ...
    );
    legend(series_name);
    title("Concentration of Free Drug in Small Tumor");
    
    nexttile;
    plot(...
        t1, y1(:, 5), ...
        t2, y2(:, 5), ...
        t3, y3(:, 5), ...
        'LineWidth', 3 ...
    );
    legend(series_name);
    title("Concentration of Free Drug in Body");
    
    nexttile
    plot(...
        t1, b1, ...
        t2, b2, ...
        t3, b3, ...
        'LineWidth', 3 ...
    );
    legend(series_name);
    title("Mass Balance");
end